### ISSUE TITLE
Farming for Blockheads (farmingforblockheads) has failed to load correctly

### ISSUE THREAD

**Issue by tetrayon** [blay09/FarmingForBlockheads#124]
## Bug Report

The game crashes when I try to load it using this mod. I haven't used the mod before.</br>

### Crash Report and Logs

-- MOD farmingforblockheads --
Details:
	Caused by 0: java.lang.NoClassDefFoundError: net/minecraft/resources/IFutureReloadListener
		at java.lang.Class.getDeclaredConstructors0(Native Method) ~[?:?] {}
		at java.lang.Class.privateGetDeclaredConstructors(Class.java:3305) ~[?:?] {}
		at java.lang.Class.getConstructor0(Class.java:3510) ~[?:?] {}
		at java.lang.Class.getDeclaredConstructor(Class.java:2691) ~[?:?] {}
		at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:81) ~[javafmllanguage-1.17.1-37.0.67.jar%2366!:?] {}
		at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:120) ~[fmlcore-1.17.1-37.0.67.jar%2365!:?] {}
		at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1800) ~[?:?] {}
		at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1792) ~[?:?] {}
		at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:295) ~[?:?] {}
		at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1016) ~[?:?] {}
		at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1665) ~[?:?] {}
		at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1598) ~[?:?] {}
		at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183) ~[?:?] {}

	Mod File: FarmingForBlockheads_1.16.5-7.3.1.jar
	Failure message: Farming for Blockheads (farmingforblockheads) has failed to load correctly
		java.lang.NoClassDefFoundError: net/minecraft/resources/IFutureReloadListener
	Mod Version: 7.3.1
	Mod Issue URL: https://github.com/blay09/FarmingForBlockheads/issues
	Exception message: java.lang.ClassNotFoundException: net.minecraft.resources.IFutureReloadListener
Stacktrace:
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:135) ~[securejarhandler-0.9.46.jar:?] {}
	at java.lang.ClassLoader.loadClass(ClassLoader.java:519) ~[?:?] {}
	at java.lang.Class.getDeclaredConstructors0(Native Method) ~[?:?] {}
	at java.lang.Class.privateGetDeclaredConstructors(Class.java:3305) ~[?:?] {}
	at java.lang.Class.getConstructor0(Class.java:3510) ~[?:?] {}
	at java.lang.Class.getDeclaredConstructor(Class.java:2691) ~[?:?] {}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:81) ~[javafmllanguage-1.17.1-37.0.67.jar%2366!:?] {}
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:120) ~[fmlcore-1.17.1-37.0.67.jar%2365!:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1800) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1792) ~[?:?] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:295) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1016) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1665) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1598) ~[?:?] {}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183) ~[?:?] {}

### Mod Version
1.16.5</br>

**Comment by BlayTheNinth** [comment]
You can't run a mod for Minecraft 1.16.5 on Minecraft 1.17.1.
