### ISSUE TITLE
Config issue

### ISSUE THREAD

**Issue by A5ho9999** [blay09/FarmingForBlockheads#188]
### Minecraft Version

1.20.x

### Mod Loader

Fabric

### Mod Loader Version

Fabric 0.14.11

### Mod Version

farmingforblockheads-fabric-1.20-14.0.0

### Balm Version

balm-fabric-1.20-7.0.4

### Describe the Issue

Config files are duplicating with .bak (I assume same issue that was already fixed in the crafting tweaks)

### Logs

```
[09:09:54] [main/ERROR]: Errors were encountered when loading the config file farmingforblockheads-common.toml:
[09:09:54] [main/ERROR]: - Error loading config property [] 'merchantNames'
java.lang.NullPointerException: null
	at java.lang.Class.isAssignableFrom(Native Method) ~[?:?]
	at net.blay09.mods.balm.fabric.config.FabricConfigLoader.convertValue(FabricConfigLoader.java:212) ~[balm-fabric-1.20-7.0.4.jar:?]
	at net.blay09.mods.balm.fabric.config.FabricConfigLoader.convertValue(FabricConfigLoader.java:199) ~[balm-fabric-1.20-7.0.4.jar:?]
	at net.blay09.mods.balm.fabric.config.FabricConfigLoader.load(FabricConfigLoader.java:59) ~[balm-fabric-1.20-7.0.4.jar:?]
	at net.blay09.mods.balm.fabric.config.FabricBalmConfig.initializeBackingConfig(FabricBalmConfig.java:26) ~[balm-fabric-1.20-7.0.4.jar:?]
	at net.blay09.mods.balm.api.config.AbstractBalmConfig.registerConfig(AbstractBalmConfig.java:80) ~[balm-fabric-1.20-7.0.4.jar:?]
	at net.blay09.mods.farmingforblockheads.FarmingForBlockheadsConfig.initialize(FarmingForBlockheadsConfig.java:20) ~[farmingforblockheads-fabric-1.20-14.0.0.jar:?]
	at net.blay09.mods.farmingforblockheads.FarmingForBlockheads.initialize(FarmingForBlockheads.java:34) ~[farmingforblockheads-fabric-1.20-14.0.0.jar:?]
	at net.blay09.mods.balm.fabric.FabricBalmRuntime.initialize(FabricBalmRuntime.java:183) ~[balm-fabric-1.20-7.0.4.jar:?]
	at net.blay09.mods.balm.api.Balm.initialize(Balm.java:35) ~[balm-fabric-1.20-7.0.4.jar:?]
	at net.blay09.mods.farmingforblockheads.FabricFarmingForBlockheads.onInitialize(FabricFarmingForBlockheads.java:9) ~[farmingforblockheads-fabric-1.20-14.0.0.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:62) ~[fabric-loader-0.14.21.jar:?]
	at net.minecraft.server.Main.main(Main.java:112) ~[server-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) ~[fabric-loader-0.14.21.jar:?]
[09:09:54] [main/ERROR]: The affected properties have been reset to their defaults and a backup of the corrupted version was created under farmingforblockheads-common.toml.bak13
```

**Comment by A5ho9999** [comment]
Provided log message
