### ISSUE TITLE
Market block doesn't work, can't interact with anything either

### ISSUE THREAD

**Issue by JustKade** [blay09/FarmingForBlockheads#198]
### Minecraft Version

1.20.x

### Mod Loader

Forge

### Mod Loader Version

47.1.47

### Mod Version

14.0.1

### Balm Version

7.0.7

### Describe the Issue

<details>
<summary>Error Message</summary>
[24Sep2023 05:50:26.024] [Server thread/ERROR] [net.minecraft.network.protocol.PacketUtils/]: Failed to handle packet net.minecraft.network.protocol.game.ServerboundContainerClickPacket@34ab04e, suppressing error
java.lang.NullPointerException: Cannot invoke "net.blay09.mods.farmingforblockheads.api.IMarketCategory.getRegistryName()" because "category" is null
	at net.blay09.mods.farmingforblockheads.network.MarketListMessage.encode(MarketListMessage.java:48) ~[farmingforblockheads-forge-1.20-14.0.1.jar%23320!/:14.0.1]
	at net.minecraftforge.network.simple.IndexedMessageCodec.lambda$tryEncode$4(IndexedMessageCodec.java:121) ~[forge-1.20.1-47.1.46-universal.jar%23428!/:?]
	at java.util.Optional.ifPresent(Optional.java:178) ~[?:?]
	at net.minecraftforge.network.simple.IndexedMessageCodec.tryEncode(IndexedMessageCodec.java:119) ~[forge-1.20.1-47.1.46-universal.jar%23428!/:?]
	at net.minecraftforge.network.simple.IndexedMessageCodec.build(IndexedMessageCodec.java:134) ~[forge-1.20.1-47.1.46-universal.jar%23428!/:?]
	at net.minecraftforge.network.simple.SimpleChannel.encodeMessage(SimpleChannel.java:68) ~[forge-1.20.1-47.1.46-universal.jar%23428!/:?]
	at net.minecraftforge.network.simple.SimpleChannel.toBuffer(SimpleChannel.java:81) ~[forge-1.20.1-47.1.46-universal.jar%23428!/:?]
	at net.minecraftforge.network.simple.SimpleChannel.toVanillaPacket(SimpleChannel.java:112) ~[forge-1.20.1-47.1.46-universal.jar%23428!/:?]
	at net.minecraftforge.network.simple.SimpleChannel.send(SimpleChannel.java:107) ~[forge-1.20.1-47.1.46-universal.jar%23428!/:?]
	at net.blay09.mods.balm.forge.network.ForgeBalmNetworking.sendTo(ForgeBalmNetworking.java:83) ~[balm-forge-1.20-7.0.7.jar%23273!/:7.0.7]
	at net.blay09.mods.farmingforblockheads.menu.MarketMenu.m_38946_(MarketMenu.java:129) ~[farmingforblockheads-forge-1.20-14.0.1.jar%23320!/:14.0.1]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.m_5914_(ServerGamePacketListenerImpl.java:1561) ~[server-1.20.1-20230612.114412-srg.jar%23423!/:?]
	at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.m_5797_(ServerboundContainerClickPacket.java:56) ~[server-1.20.1-20230612.114412-srg.jar%23423!/:?]
	at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.m_5797_(ServerboundContainerClickPacket.java:12) ~[server-1.20.1-20230612.114412-srg.jar%23423!/:?]
	at net.minecraft.network.protocol.PacketUtils.m_263899_(PacketUtils.java:22) ~[server-1.20.1-20230612.114412-srg.jar%23423!/:?]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[server-1.20.1-20230612.114412-srg.jar%23423!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:156) ~[server-1.20.1-20230612.114412-srg.jar%23423!/:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23) ~[server-1.20.1-20230612.114412-srg.jar%23423!/:?]
	at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:770) ~[server-1.20.1-20230612.114412-srg.jar%23423!/:?]
	at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:161) ~[server-1.20.1-20230612.114412-srg.jar%23423!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:130) ~[server-1.20.1-20230612.114412-srg.jar%23423!/:?]
	at net.minecraft.server.MinecraftServer.m_129961_(MinecraftServer.java:753) ~[server-1.20.1-20230612.114412-srg.jar%23423!/:?]
	at net.minecraft.server.MinecraftServer.m_7245_(MinecraftServer.java:747) ~[server-1.20.1-20230612.114412-srg.jar%23423!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_18699_(BlockableEventLoop.java:115) ~[server-1.20.1-20230612.114412-srg.jar%23423!/:?]
	at net.minecraft.server.MinecraftServer.m_130012_(MinecraftServer.java:732) ~[server-1.20.1-20230612.114412-srg.jar%23423!/:?]
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:665) ~[server-1.20.1-20230612.114412-srg.jar%23423!/:?]
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:251) ~[server-1.20.1-20230612.114412-srg.jar%23423!/:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
</details>

I get this error message on my server I run. It happens whenever someone tries and accesses it inside of a claimed area with Open Parties and Claims but it also doesn't work outside of the claimed area either. That's the only error message I get when checking the debug log. I've linked the latest log file to see if that helps as well.

### Logs

https://mclo.gs/RzJBg5g

### Do you use any performance-enhancing mods (e.g. OptiFine) or custom server distributions (e.g. SpongeForge)?

Rubidium, ModernFix

**Comment by BlayTheNinth** [comment]
Somehow, your market entries have no category and the vanilla fallback category ("Other") does not exist. This should be impossible unless some mod is misusing the Farming for Blockheads API in very odd ways. Or maybe something is preventing the market registry events from being handled correctly. But it's difficult to say what exactly the cause could be.
